In [ ]:
from google.colab import files
uploaded = files.upload()

Saving books_dataset.xlsx to books_dataset.xlsx

In [ ]:
import pandas as pd

df = pd.read_excel("books_dataset.xlsx")

df.head()

                                   Title    Price Rating
0                   A Light in the Attic  Â£51.77  Three
1                     Tipping the Velvet  Â£53.74    One
2                             Soumission  Â£50.10    One
3                          Sharp Objects  Â£47.82   Four
4  Sapiens: A Brief History of Humankind  Â£54.23   Five

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   1000 non-null   object
 1   Price   1000 non-null   object
 2   Rating  1000 non-null   object
dtypes: object(3)
memory usage: 23.6+ KB

In [ ]:
df.shape

(1000, 3)

In [ ]:
df.isnull().sum()

Title     0
Price     0
Rating    0
dtype: int64

In [ ]:
df["Rating"].value_counts()

Rating
One      226
Three    203
Five     196
Two      196
Four     179
Name: count, dtype: int64

In [ ]:
df["Price"] = df["Price"].astype(str)

df["Price"] = (
    df["Price"]
    .str.replace("£", "", regex=False)
    .str.replace("Â", "", regex=False)
)

df["Price"] = pd.to_numeric(df["Price"])

In [ ]:
df["Price"].describe()

count    1000.00000
mean       35.07035
std        14.44669
min        10.00000
25%        22.10750
50%        35.98000
75%        47.45750
max        59.99000
Name: Price, dtype: float64

In [ ]:
df.loc[df["Price"].idxmax()]

Title     The Perfect Play (Play by Play #1)
Price                                  59.99
Rating                                 Three
Name: 648, dtype: object

In [ ]:
df.sort_values(by="Price", ascending=False).head(10)

                                                 Title  Price Rating
648                 The Perfect Play (Play by Play #1)  59.99  Three
617                  Last One Home (New Beginnings #1)  59.98  Three
860                   Civilization and Its Discontents  59.95    Two
560                     The Barefoot Contessa Cookbook  59.92   Five
366                          The Diary of a Young Girl  59.90  Three
657  The Bone Hunters (Lexy Vaughan & Steven Macaul...  59.71  Three
133  Thomas Jefferson and the Tripoli Pirates: The ...  59.64    One
387                      Boar Island (Anna Pigeon #19)  59.48  Three
549  The Man Who Mistook His Wife for a Hat and Oth...  59.45   Four
393                          The Improbability of Love  59.45    One